@startuml
class Faction{
    
    List<FactionAbilities>
}

/'Abilities'/
class AbilitiesLoader {
    String id
    String name
    String faction_id
    String description
}

class FactionAbilities {
    String name
    String description
}

class Abilities {
    String name
    String description
}

/'Datasheets'/
Enum datasheetRole {
    Battleline
}

/'
transportCapacity = transport
leaderRules = leader_footer
damagedWound = damaged_W 
damagedDescription = damaged_description
'/
class DatasheetLoader {
    String id
    String name
    String faction_id
    datasheetRole role
    String loadout
    String transportCapacity
    String leaderRules 
    String damagedWound
    String damagedDescription
    String link
}

class Datasheet {
    String css (the css neded for all its elements)
}

/'Datasheets_abillities'/
Enum AbillitiesType{
    Core,
    Faction,
    Datasheet,
    Special (правая колонка) (at the bottom)
    more...
}

class DatasheetAbillitesLoader{
    String datasheetId
    int tabelLineNumber
    String abilityId?
    String Model?
    String name
    String description?
    AbillitiesType type
    String parameter?
}

/'Datasheets_detachment_abillities'/
class DatasheetsDetachmentAbillitiesRelationLoader {
    int datasheetId
    int detachmentId
}

/'Datasheets_enhancements'/
class DatasheetsEnhancementsRelationLoader {
    int datasheet_Id
    int enhancment_Id
}

/'Datasheets_keywords'/
class DatasheetKeywordsLoader {
    int datasheet_id
    string keyword
    string model?
    boolean is_faction_keyword
}

/'Datasheets_leader'/
class DatasheetLeaderLoader {
    int leader_id (leader datasheet)
    int attached_id (which ones they can lead)
}

/'Datasheets_models (stats)'/
'if data not present "-"
class DatasheetsModelLoader {
    string datasheet_id
    int line
    string name
    string M
    string T
    string Sv
    string inv_sv? 
    string inv_sv_descr?
    string W
    string Ld
    string OC
}

/'Datasheets_models_cost'/
class DatasheetModelsCostLoader {
    string datasheet_id
    int line
    string description
    string cost
}

/'Daatasheets_options (Wargear options)'/
class DataSheetWargearOptionsLoader {
    string datasheet_id
    int line
    string description
}

/'Datasheets_stratagems'/
class DatasheetsStratagemsRelationLoader {
    string datasheet_Id
    string stratagem_id
}

/'Datasheets_unit_composition'/
class DatasheetsUnitCompositionLoader {
    string datasheet_id
    int line
    string description
}

/'Datasheets_wargear'/
class DatasheetsWargearLoader {
    string datasheet_id
    int line
    string dice (if dice is nesesariy for chossing the weapon option(check Bubblechukka - ork, Mek Gunz))
    string name
    string description
    string range
    string type
    string A
    string BS_WS
    string S
    string AP
    string D
}

/'Detachment_abilities'/
class DetachmentAbilitiesLoader {
    string id
    string faction_id
    string name
    string description
    string detachment
}


class Unit {

}


class Model {
}

class Weapon{
    String name
    ArrayList<WeaponAttributes> attributes
    String attacks
    int balisticSkill
    int strength
    int armorPenetration
    String damgage

}

class RangedWeapon{
    Int range
}

class MeleeWeapon{

}

Enum WeaponAttributes{
    Name, ImageExplenation
}

@enduml