@startuml
'missing fation abilities, no way as of right know to include it'
class FactionModel {
    String id
    String name
    String wahpediaLink
    List<Detachments>
    List<Datasheets>
}

FactionModel --> Detachment
FactionModel --> Datasheet

class DetachmentModel {
    String Id
    FactionModel Faction
    String name
    List<Stratgems>
    List<Enhacments>
    List<DetachmentAbillity>
}

Detachment --> Stratagem
Detachment --> Enhacment
Detachment --> DetachmentAbillity

class DetachmentAbillityModel  {
    String id
    String DetachmentId
    String name
    String descreption
}

class Stratagem {
    String id
    String DetachmentId
    String name
    StratagemType type
    int cpCost
    TurnType turnToBeUsed
    List<Phase> phasesToBeUsed
    String descreption
}

Stratagem --> StratagemType
Stratagem --> TurnType
Stratagem --> Phase

Enum StratagemType {

}

Enum TurnType {

}

Enum Phase {
    
}

class Enhacment {
    String id
    String DetachmentId
    String name
    String descreption
    int pointsCost
}

class Datasheet {

}

@enduml